# Generated by Django 5.0.2 on 2024-02-27 12:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bolim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomi', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Xabarlar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('xabar_turi', models.CharField(choices=[('ariza', 'Ariza'), ('tatil', 'Tatil')], max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Shaxs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ism', models.CharField(max_length=10)),
                ('familiya', models.CharField(max_length=100)),
                ('tel', models.CharField(max_length=100, unique=True)),
                ('address', models.CharField(max_length=255)),
                ('qoshilgan_vaqt', models.DateTimeField(auto_now_add=True)),
                ('bolim', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='allegro.bolim')),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mavzu', models.CharField(max_length=200)),
                ('tarkib', models.TextField()),
                ('qoshilgan_vaqt', models.DateTimeField(auto_now_add=True)),
                ('jonatuvchi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_messages', to='allegro.shaxs')),
                ('oluvchi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_messages', to='allegro.shaxs')),
            ],
        ),
        migrations.CreateModel(
            name='Ariza',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shaxs', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='allegro.shaxs')),
                ('xabar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='xabarlar', to='allegro.xabarlar')),
            ],
        ),
    ]
